### PR TITLE
I think we should add a file for Hong Kong, China

### PR DESCRIPTION
**Pull request by GlennWong-BedBath**
This file needs to go though the workflow:
- [] Create branch
- [] Add some commits
- [] Open a pull request
- [] Have a discussion
- [] Merge my pull request

### CODE REVIEW

**Comment by ggorla** [comment]
Hong Kong thats sounds fun :tada:

**Comment by sreekanthmelam** [comment]
Glenn, please add more details about hongkong

**Comment by GlennWong-BedBath** [comment]
Dim sum is good.  Many choices.

**Comment by GlennVV** [comment]
Disneyland is there.

**Pull request merged**
